version: '3.5'

# For this configuration to work properly, you must have a license file mounted into the dotcms service.
# Without a license file, the external ES service will NOT be recognized and utilized.  All documents will
# indexed on the dotcms node directly and will not be persisted between restarts.

networks:
  http_net:
  db_net:
  es_net:

volumes:
  cms-shared:
  #cms-local:
  dbdata:
  esdata:

services:
  http:
    image: dotcms/haproxy:1.8-os
    environment:
      "HAPROXY_CERT_PATH": '/certs/'
#      "HAPROXY_REDIRECT_HTTPS_ALL": 'true'
#      "HAPROXY_MAINTENANCE_PAGE": '/srv/config/503.http'

    ports:
      - "80:8080"
      - "443:8443"
#    volumes:
#      - /data/dotcms/haproxy/certs:/certs:ro
#      - /data/dotcms/haproxy/503.http:/srv/config/503.http:ro

    networks:
      - http_net

  elasticsearch:
    image: gcr.io/cicd-246518/es-open-distro:1.3.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1500m'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '2'
      "ES_ADMIN_PASSWORD": 'admin'
      discovery.type: single-node
    volumes:
      - esdata:/data
    networks:
      - es_net

  dotcms:
    image: dotcms/dotcms:latest
    environment:
      "CMS_HEAP_SIZE": '2g'
      "CMS_JAVA_OPTS": '-XX:+PrintFlagsFinal'
      "PROVIDER_DB_DNSNAME": 'db'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch'
      "ES_ADMIN_PASSWORD": 'admin'
    depends_on:
      - elasticsearch
      - db
      - http
    volumes:
      - cms-shared:/data/shared
      #- [serverpath]/license.dat:/data/local/dotsecure/license/license.dat
      #- [serverpath]/license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - http_net
      - es_net

  db:
    image: bitnami/postgresql:11
    environment:
      "POSTGRESQL_USERNAME": 'dotcmsdbuser'
      "POSTGRESQL_PASSWORD": 'password'
      "POSTGRESQL_DATABASE": 'dotcms'
    volumes:
      - dbdata:/bitnami/postgresql
    networks:
      - db_net
