#!/usr/bin/with-contenv /bin/sh

set -e 

source /srv/docker-container/utils/config-defaults.sh

if [[ -z "${PROVIDER_ELASTICSEARCH_DNSNAMES}" ]]; then
    while true; do 
        sleep 86400
    done
else
    echo "Starting background Elasticsearch discovery..."
    exec /srv/docker-container/utils/es-bg-discovery.sh
fi
