version: '3.5'

networks:
  http_net:
  db_net:
  es_net:

volumes:
  cms-shared:
  dbdata:
  esdata:

services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.6.0
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=localhost
      - cluster.initial_master_nodes=odfe-node1
      - data
      - bootstrap.memory_lock=true 
      - "ES_JAVA_OPTS=-Xmx1G " 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es_net

  dotcms:
    image: dotcms/dotcms:latest
    environment:
      "CMS_HEAP_SIZE": '1g'
      "CMS_JAVA_OPTS": '-XX:+PrintFlagsFinal'
      "PROVIDER_DB_DNSNAME": 'db'
      "PROVIDER_ELASTICSEARCH_ENDPOINTS": 'https://elasticsearch:9200'
      "ES_ADMIN_PASSWORD": 'admin'
      "CUSTOM_STARTER_URL": 'https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20200512/starter-20200512.zip'
    depends_on:
      - elasticsearch
      - db
    volumes:
      - cms-shared:/data/shared
      #- [serverpath]/license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - es_net
    ports:
      - "8080:8081"
      - "8443:8082"

  db:
    image: postgres:11
    command: postgres -c 'max_connections=500' -c 'shared_buffers=128MB'
    environment:
        "POSTGRES_USER": 'dotcmsdbuser'
        "POSTGRES_PASSWORD": 'password'
        "POSTGRES_DB": 'dotcms'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db_net
